Feature/12 server creation
JohanCDev/R-Type pull request #34
Opened 2022-10-17 14:04 UTC by Djadanis

2022-10-17 14:20 UTC, tbellicha approved these changes

2022-10-17 15:33 UTC, CedricCORGE approved these changes

2022-10-17 15:52 UTC, JohanCDev requested changes

2022-10-17 15:52 UTC, JohanCDev commented on dependencies/Makefile
> +# CMAKE generated file: DO NOT EDIT!
Useless file

2022-10-17 15:52 UTC, JohanCDev commented on dependencies/cmake_install.cmake
> +# Install script for directory: /workspaces/R-Type/dependencies
Useless file

2022-10-17 15:52 UTC, JohanCDev commented on src/Common/Message/Message.h
> + * @author your name (you@domain.com)
Missing information

2022-10-17 15:52 UTC, JohanCDev commented on src/Common/Message/MessageHeader.h
> + * @author your name (you@domain.com)
Missing information

2022-10-17 15:52 UTC, JohanCDev commented on src/Common/Message/MessageType.h
> + * @author your name (you@domain.com)
Missing information

2022-10-17 15:52 UTC, JohanCDev commented on src/Common/locked_queue.h
> + * @author your name (you@domain.com)
Missing information

2022-10-17 15:52 UTC, JohanCDev commented on src/ECS/ResourcesManager.cpp
> + * @author your name (you@domain.com)
Missing information

2022-10-17 15:52 UTC, JohanCDev commented on src/client/client.cpp
> + * @author your name (you@domain.com)
Missing information

2022-10-17 15:52 UTC, JohanCDev commented on src/client/client.hpp
> + * @author your name (you@domain.com)
Missing information

2022-10-17 15:52 UTC, JohanCDev commented on src/server/main2.cpp
> +/**
Weird name for a main file

2022-10-18 15:52 UTC, Djadanis commented
Displaced this PR

2022-10-18 15:52 UTC, closed without merging