Doc/43 ecs documentation
JohanCDev/R-Type pull request #45
Opened 2022-10-21 12:26 UTC by CedricCORGE

2022-10-21 12:36 UTC, CedricCORGE commented on .github/workflows/build.yml
> +          mkdir -p build; cd build && conan install .. --build=missing  -s compiler.libcxx=libstdc++11 -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True && cmake
without this build fail on raspberry probably due to too many core use

2022-10-21 12:36 UTC, CedricCORGE commented on .github/workflows/build.yml
> +          mkdir -p build; cd build && conan install .. --build=missing  -s compiler.libcxx=libstdc++11 -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True && cmake
so i limit to 1 core

2022-10-21 12:41 UTC, tbellicha requested changes

2022-10-21 12:41 UTC, tbellicha commented on src/ECS/Components/DrawableComponent.hpp
>  struct Vector4 {
Why a Vector4 only contains 2 members ?

2022-10-21 12:41 UTC, tbellicha commented on src/ECS/Registry.hpp
> +     * @param func
What is a "func" ?

2022-10-25 09:53 UTC, JohanCDev approved these changes

2022-10-25 09:54 UTC, tbellicha approved these changes

2022-10-25 10:18 UTC, merged