96/player level up
JohanCDev/R-Type pull request #99
Opened 2022-11-09 13:20 UTC by Djadanis

2022-11-09 14:20 UTC, tbellicha approved these changes

2022-11-09 15:06 UTC, CedricCORGE requested changes

2022-11-09 15:06 UTC, CedricCORGE commented on src/ECS/Components/WeaponComponent.hpp
> +    uint32_t damage;
restore the Vector2i for stat

2022-11-09 15:06 UTC, CedricCORGE commented on src/ECS/World.cpp
> +        ent, WeaponComponent("meteor", defaultValues[GameObject::ENEMY_FOCUS].atk, /*1,*/ 0));
Comment here also

2022-11-11 13:57 UTC, JohanCDev approved these changes

2022-11-11 13:59 UTC, CedricCORGE approved these changes

2022-11-11 14:07 UTC, merged